/**
 * Read access to the law corpus: the 75 provision records of the Act and the
 * Rules, and the glossary drawn from their definitions clauses.
 *
 * Everything a provision page or index renders comes through here, so the
 * URL scheme, display labels and ordering live in one place. The JSON is
 * generated by scripts/sync-law.mjs and is never edited by hand.
 */
import data from "../data/law/provisions.json";
import glossary from "../data/law/glossary.json";

export const DOCS = {
  act: {
    key: "act",
    short: "The Act",
    name: data.meta.act.document,
    shortName: "DPDPA 2023",
    route: "/act",
    legislationDate: "2023-08-11",
    legislationType: "Act of Parliament"
  },
  rules: {
    key: "rules",
    short: "The Rules",
    name: data.meta.rules.document,
    shortName: "DPDP Rules 2025",
    route: "/rules",
    legislationDate: "2025-11-13",
    legislationType: "Statutory rules"
  }
};

export const CHAPTERS = [
  { numeral: "I", title: "Preliminary", from: 1, to: 3 },
  { numeral: "II", title: "Obligations of Data Fiduciary", from: 4, to: 10 },
  { numeral: "III", title: "Rights and duties of Data Principal", from: 11, to: 15 },
  { numeral: "IV", title: "Special provisions", from: 16, to: 17 },
  { numeral: "V", title: "Data Protection Board of India", from: 18, to: 26 },
  { numeral: "VI", title: "Powers, functions and procedure to be followed by Board", from: 27, to: 28 },
  { numeral: "VII", title: "Appeal and alternate dispute resolution", from: 29, to: 32 },
  { numeral: "VIII", title: "Penalties and adjudication", from: 33, to: 34 },
  { numeral: "IX", title: "Miscellaneous", from: 35, to: 44 }
];

const ORDINALS = ["first", "second", "third", "fourth", "fifth", "sixth", "seventh"];
const ORDINAL_WORD = { first: "First", second: "Second", third: "Third", fourth: "Fourth", fifth: "Fifth", sixth: "Sixth", seventh: "Seventh" };

/* Document order: sections, the Schedule, rules, then the rules' schedules. */
const ORDER = [
  ...Array.from({ length: 44 }, (_, i) => `S${i + 1}`),
  "ACT-SCHEDULE",
  ...Array.from({ length: 23 }, (_, i) => `R${i + 1}`),
  ...ORDINALS.map((o) => `SCH-${o.toUpperCase()}`)
];

const BY_LABEL = Object.fromEntries(data.provisions.map((p) => [p.label, p]));
const PROVISIONS = ORDER.map((l) => BY_LABEL[l]).filter(Boolean);

export function listProvisions() {
  return PROVISIONS;
}

export function getProvision(label) {
  return BY_LABEL[label] || null;
}

export function documentOf(p) {
  return p.kind === "section" || p.kind === "act-schedule" ? DOCS.act : DOCS.rules;
}

/** "Section 6", "The Schedule", "Rule 7", "First Schedule". */
export function displayLabel(p) {
  switch (p.kind) {
    case "section": return `Section ${p.number}`;
    case "rule": return `Rule ${p.number}`;
    case "act-schedule": return "The Schedule";
    default: return `${ORDINAL_WORD[ordinalOf(p.label)]} Schedule`;
  }
}

function ordinalOf(label) {
  return label.replace(/^SCH-/, "").toLowerCase();
}

/** The chapter a section sits in, or null for anything that is not a section. */
export function chapterOf(p) {
  if (p.kind !== "section") return null;
  return CHAPTERS.find((c) => p.number >= c.from && p.number <= c.to) || null;
}

/** Public path for a provision label. */
export function routeFor(label) {
  const p = typeof label === "string" ? BY_LABEL[label] : label;
  if (!p) return null;
  switch (p.kind) {
    case "section": return `/act/section-${p.number}`;
    case "act-schedule": return "/act/schedule";
    case "rule": return `/rules/rule-${p.number}`;
    default: return `/rules/schedule-${ordinalOf(p.label)}`;
  }
}

const BY_ROUTE = Object.fromEntries(PROVISIONS.map((p) => [routeFor(p), p]));

export function provisionRoutes() {
  return PROVISIONS.map((p) => routeFor(p));
}

export function getByRoute(path) {
  const clean = String(path || "").replace(/\/+$/, "") || "/";
  return BY_ROUTE[clean] || null;
}

/**
 * Label for a citation as people write it: "Section 6", "Section 6(4)",
 * "Rule 7", "the Schedule", "First Schedule". Null when it names nothing.
 */
export function labelFor(displayText) {
  const s = String(displayText || "").trim();
  let m = /^(?:section|sec\.?|s\.?)\s*(\d{1,2})\b/i.exec(s);
  if (m) return BY_LABEL[`S${m[1]}`] ? `S${m[1]}` : null;
  m = /^(?:rule|r\.?)\s*(\d{1,2})\b/i.exec(s);
  if (m) return BY_LABEL[`R${m[1]}`] ? `R${m[1]}` : null;
  m = /^(?:the\s+)?(first|second|third|fourth|fifth|sixth|seventh)\s+schedule\b/i.exec(s);
  if (m) return `SCH-${m[1].toUpperCase()}`;
  if (/^(?:the\s+)?schedule\b/i.test(s)) return "ACT-SCHEDULE";
  return null;
}

/** Previous and next provision within the same document. */
export function neighbours(p) {
  const doc = documentOf(p);
  const siblings = PROVISIONS.filter((q) => documentOf(q) === doc);
  const i = siblings.indexOf(p);
  return { prev: siblings[i - 1] || null, next: siblings[i + 1] || null };
}

/* ── Dates ────────────────────────────────────────────────────────── */

const MONTHS = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];

/** "2027-05-13" → "13 May 2027". Done by hand so the output does not depend on the build machine's locale. */
export function formatDate(iso) {
  const m = /^(\d{4})-(\d{2})-(\d{2})/.exec(String(iso || ""));
  if (!m) return "";
  return `${Number(m[3])} ${MONTHS[Number(m[2]) - 1]} ${Number(m[1])}`;
}

/** True/false when the record carries a commencement date; null when the date is not known. */
export function isInForce(p, onDate = new Date()) {
  if (!p.in_force_from) return null;
  return new Date(`${p.in_force_from}T00:00:00Z`).getTime() <= onDate.getTime();
}

/** The commencement badge for a provision, or null when nothing verified can be said. */
export function commencement(p, onDate = new Date()) {
  const inForce = isInForce(p, onDate);
  if (inForce === null) return null;
  const date = formatDate(p.in_force_from);
  return inForce
    ? { status: "in-force", date, label: `In force since ${date}` }
    : { status: "future", date, label: `Applies from ${date}` };
}

/* ── Clause lines ─────────────────────────────────────────────────── */

/* The gazette text arrives as one run of prose. Sub-clauses are easier to
   read on their own lines, so the text is split *before* each marker with
   zero-width lookaheads: nothing is removed or moved, and joining the lines
   gives back the original string byte for byte.

   A marker preceded by "sub-section" or "clause", or by another marker and
   a conjunction ("(1) and (2)", "(a), (b)"), is a cross-reference inside a
   sentence, not the start of a sub-clause, so it stays inline. */
const NOT_A_REF = "(?<!\\b(?:sub-sections?|sub-rules?|sub-clauses?|sections?|rules?|clauses?|items?|paragraphs?))(?<!\\)\\s?(?:and|or|to))(?<!,)";
const MARKERS = [
  `${NOT_A_REF}(?= \\(\\d{1,2}\\) )`,
  `${NOT_A_REF}(?= \\([a-z]{1,4}\\) )`,
  "(?<!\\b(?:sections?|rules?|clauses?|items?|paragraphs?|PART|Part))(?= \\d{1,2}\\. (?=[A-Z“]))",
  "(?= PART [A-Z]\\b)",
  "(?= Illustration\\.)"
].join("|");
const SPLIT = new RegExp(MARKERS, "g");

const ROMAN = /^(i{1,3}|iv|v|vi{1,3}|ix|x|xi{1,3})$/;

function markerOf(line) {
  let m = /^\s*\((\d{1,2}|[a-z]{1,4})\)/.exec(line);
  if (m) return m[1];
  m = /^\s*(\d{1,2})\./.exec(line);
  if (m) return m[1];
  if (/^\s*PART [A-Z]\b/.test(line)) return "PART";
  if (/^\s*Illustration\./.test(line)) return "Illustration";
  return null;
}

/* Depth of a sub-clause from its marker. "(i)" is a Roman sub-sub-clause
   unless it follows "(h)", "(v)" is Roman only after "(iv)", and so on. */
function depthOf(marker, prev) {
  if (marker === null || marker === "PART" || marker === "Illustration") return 0;
  if (/^\d+$/.test(marker)) return 0;
  if (ROMAN.test(marker)) {
    if (marker === "i" && prev === "h") return 1;
    if (marker === "v" && prev !== "iv") return 1;
    if (marker === "x" && prev !== "ix") return 1;
    return 2;
  }
  return 1;
}

/**
 * The provision text as display lines: [{ text, depth, kind }].
 * `lines.map(l => l.text).join("")` is exactly the input.
 */
export function clauseLines(text) {
  const parts = String(text).split(SPLIT).filter((s) => s.length > 0);
  // A bare "6." before the first sub-section is not worth a line of its own.
  if (parts.length > 1 && parts[0].trim().length <= 4) parts.splice(0, 2, parts[0] + parts[1]);

  const out = [];
  let prev = null;
  for (const part of parts) {
    const marker = markerOf(part);
    const depth = depthOf(marker, prev);
    const kind = marker === "Illustration" ? "illustration" : marker === "PART" ? "part" : out.length === 0 ? "lead" : "clause";
    out.push({ text: part, depth, kind });
    if (marker && marker !== "Illustration") prev = marker;
  }
  return out;
}

/* ── Page copy shared by the screen and the head tags ─────────────── */

export const ACT_INDEX_TITLE = "The Act — 44 sections and the Schedule | DPDPA 2023 | DPDPA Wiki";
export const RULES_INDEX_TITLE = "The Rules — 23 rules and 7 schedules | DPDP Rules 2025 | DPDPA Wiki";
export const GLOSSARY_TITLE = "Glossary — every term defined in Section 2 and Rule 2 | DPDPA 2023 | DPDPA Wiki";

/** "core-rules" → "Core Rules". */
export function moduleTitle(slug) {
  return String(slug || "").split("-").map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(" ");
}

/** The h1 and <title> text before the site suffix: "Section 6 — Consent". */
export function heading(p) {
  if (p.kind === "act-schedule") return "The Schedule — Penalties";
  if (p.kind === "rules-schedule") {
    const see = /\((see .+)\)$/i.exec(p.title);
    return `${displayLabel(p)} — ${see ? see[1].charAt(0).toUpperCase() + see[1].slice(1) : p.title}`;
  }
  return `${displayLabel(p)} — ${p.title}`;
}

export function pageTitle(p) {
  return `${heading(p)} | ${documentOf(p).shortName} | DPDPA Wiki`;
}

/** The first ~155 characters of a text, cut at a word boundary. */
export function excerpt(text, max = 155) {
  const s = String(text || "").replace(/\s+/g, " ").trim();
  if (s.length <= max) return s;
  const cut = s.slice(0, max + 1);
  const at = cut.lastIndexOf(" ");
  return `${cut.slice(0, at > 60 ? at : max).replace(/[,;:—–-]+$/, "")}…`;
}

/** Short source line: "SHA-256 4deb23981d30…". */
export function shortHash(sha256) {
  return `${String(sha256 || "").slice(0, 12)}…`;
}

/* ── Glossary ─────────────────────────────────────────────────────── */

const GLOSSARY = [...glossary].sort((a, b) => a.term.localeCompare(b.term, "en", { sensitivity: "base" }));
const TERM_BY_SLUG = Object.fromEntries(GLOSSARY.map((g) => [g.slug, g]));

export function listGlossary() {
  return GLOSSARY;
}

export function getTerm(slug) {
  return TERM_BY_SLUG[slug] || null;
}

export function glossaryRoutes() {
  return GLOSSARY.map((g) => `/glossary/${g.slug}`);
}

/** Entries grouped by initial letter, in alphabetical order. */
export function glossaryGroups() {
  const groups = new Map();
  for (const g of GLOSSARY) {
    const letter = g.term.charAt(0).toUpperCase();
    if (!groups.has(letter)) groups.set(letter, []);
    groups.get(letter).push(g);
  }
  return [...groups.entries()].map(([letter, terms]) => ({ letter, terms }));
}

export function glossaryTitle(g) {
  return `${g.term} — definition, ${g.clause} | ${g.provision === "S2" ? DOCS.act.shortName : DOCS.rules.shortName} | DPDPA Wiki`;
}
